# Generated by Django 5.0.3 on 2024-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_dest_delete_funn'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dest',
            name='email',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dest',
            name='password',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dest',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
